lis = []
print("Empty list :",lis)
lis.insert(0,10)
print("list elements :",lis)
lis.insert(1,20)
print("list elements : ",lis)
lis.remove(20)
print("After removing element :",lis)
lis.append(30)
print("After append :",lis)
lis.sort()
print("After sort:",lis)
lis.pop()
print("After pop :",lis)
lis.append(50)
lis.reverse()
print("After reverse :",lis)